apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dummy-smon
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: dummy-svc
  endpoints:
  - port: dummy-port
    interval: 5s

