apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ddr-data-reader-smon
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: ddr-data-reader
  endpoints:
  - port: dr-data-reader-port