apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ddr-react-frontend-smon
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: ddr-react-frontend-svc
  endpoints:
    - port: dr-react-frontend-port
