# use nodejs latest docker image
# FROM --platform=linux/amd64 node:latest
FROM node:latest

# specify app directory
WORKDIR /app

# copy and install dependencies
COPY package*.json ./
RUN npm install

# bundle app source
COPY . .

EXPOSE 80
EXPOSE 443
EXPOSE 8443
EXPOSE 8080
EXPOSE 8081
CMD [ "npm", "run", "start" ]