apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ddr-data-writer-smon
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: ddr-data-writer-svc
  endpoints:
    - port: ddr-data-writer-port
      interval: 5s

