# use nodejs latest docker image
FROM --platform=linux/amd64 node:latest

# specify app directory
WORKDIR /app

# copy and install dependencies
COPY package*.json ./
RUN npm install
RUN npm install serve -g

# bundle app source
COPY . .

EXPOSE 80
EXPOSE 443
EXPOSE 8443
EXPOSE 8080
EXPOSE 3000
CMD [ "serve", "-l", "80", "-s", "build" ]