apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-cert-prod
  namespace: istio-system
spec:
  secretName: domain-cert-prod
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  # isCA: false
  # privateKey:
  #   algorithm: RSA
  #   encoding: PKCS1
  #   size: 2048
  dnsNames:
    - "ddr.gke.yxchia.me"
    - "datareader.gke.yxchia.me"
    - "datawriter.gke.yxchia.me"
    - "prometheus.gke.yxchia.me"
    - "grafana.gke.yxchia.me"
    - "alertmanager.gke.yxchia.me"
    - "dummy.gke.yxchia.me"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io