apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: receiver-cert-prod
  namespace: istio-system
spec:
  secretName: receiver-cert-prod
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  # isCA: false
  # privateKey:
  #   algorithm: RSA
  #   encoding: PKCS1
  #   size: 2048
  dnsNames:
    - "dummy.gke.1234201.xyz"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io